
training:
  - task: classification
  - project: natural-image-classification
  - num_epochs: 20
  - device: cuda
  - optimizer:
        - name: Adam
        - lr: 0.0001
        - betas: [0.9, 0.999]
        - weight_decay: 0

  - learning_rate_scheduler:
        - name: stepLR
        - step_size: 2
        - gamma: 0.1

  - earlystoping_after: 10
  - monitor_metric:
      name: val_accuracy
      mode: max

  - export:
      - format: onnx
      - input_shape: [1, 3, 256, 256]

  - PostTrainingQuantization:
      - method: BasicQuantization #TODO: add Quantization with accuracy controle (OpenVINO)
      - params:
            - model_type: None
            - preset: PERFORMANCE
            - fast_bias_correction: True
            - subset_size: 300
            - target_device: GPU

  - experiment_tracker:
      name: wandb
      credentials:
            key: 6bad4f2e0e95951572a88dc222790f1b9b732530
