
training:
  - task: binary-semantic-segmentation
  - project: WBC-segmentation
  - num_epochs: 20
  - device: cuda
  - criterion: BceLoss
  - optimizer:
        - name: Adam
        - lr: 0.0001
        - betas: [0.9, 0.999]
        - weight_decay: 0

  - learning_rate_scheduler:
        - name: stepLR
        - step_size: 2
        - gamma: 0.1

  - earlystoping_after: 10
  - monitor_metric:
      name: val_dice_score
      mode: max
  - experiment_tracker:
      name: wandb
      credentials:
            key: 6bad4f2e0e95951572a88dc222790f1b9b732530
